import type { HybridRankingDto, RankedPatentCandidate } from '../dto/rag.dto.js';

/**
 * Incoming request payload for RAG novelty analysis.
 */
export interface RagAnalysisRequest {
  query: string;
  topK?: number | undefined;
}

/**
 * Summary representation of a retrieved prior-art patent included in the RAG response.
 */
export interface RagRetrievedPatent {
  patentId: string;
  title: string;
  score: number;
  ipc?: string | undefined;
  abstract?: string | undefined;
  section?: string | undefined;
}

/**
 * Individual similar patent reference item in the novelty report.
 */
export interface SimilarPatentItem {
  patentId: string;
  reason: string;
}

/**
 * Feature comparison breakdown comparing user invention features against retrieved patents.
 */
export interface FeatureComparison {
  commonFeatures: string[];
  uniqueFeatures: string[];
  partialOverlap: string[];
}

/**
 * Grounded 7-section AI novelty analysis result generated by Qwen.
 */
export interface NoveltyAnalysisResult {
  summary: string;
  similarPatents: SimilarPatentItem[];
  featureComparison: FeatureComparison;
  novelAspects: string[];
  overlappingClaims: string[];
  risks: string[];
  recommendations: string[];
}

export type RagAnalysisResult = NoveltyAnalysisResult;

/**
 * Execution latency metrics for the RAG pipeline.
 */
export interface RagMetrics {
  retrievalTimeMs: number;
  promptTimeMs: number;
  llmInferenceTimeMs: number;
  totalTimeMs: number;
  retrievedCount: number;
}

/**
 * Full response payload returned by POST /api/rag/analyze.
 */
export interface RagAnalysisResponse {
  success: boolean;
  query: string;
  retrievedPatents?: RagRetrievedPatent[] | undefined;
  analysis: NoveltyAnalysisResult;
  metrics?: RagMetrics | undefined;
}

/**
 * Primary RAG Service Contract.
 */
export interface IRagService {
  /**
   * Performs retrieval-augmented generation novelty analysis on a user invention query.
   */
  analyze(request: RagAnalysisRequest): Promise<RagAnalysisResponse>;

  /**
   * Backward-compatible hybrid ranking method.
   */
  hybridRank(dto: HybridRankingDto): Promise<RankedPatentCandidate[]>;

  /**
   * Backward-compatible cross-encoder reranking method.
   */
  rerankCrossEncoder(candidates: RankedPatentCandidate[], topK?: number): Promise<RankedPatentCandidate[]>;
}

/**
 * Novelty Analysis Service Contract.
 */
export interface INoveltyAnalysisService {
  analyzeNovelty(request: RagAnalysisRequest): Promise<RagAnalysisResponse>;
}
