import type { HybridRankingDto, RankedPatentCandidate } from '../dto/rag.dto.js';
import type { SearchResult } from '../../search/interfaces/search.interface.js';

/**
 * Incoming request payload for RAG novelty & section/claim overlap analysis.
 */
export interface RagAnalysisRequest {
  query: string;
  topK?: number | undefined;
}

/**
 * Summary representation of a retrieved prior-art patent included in the RAG response.
 */
export interface RagRetrievedPatent {
  patentId: string;
  title: string;
  score: number;
  ipc?: string | undefined;
  abstract?: string | undefined;
  section?: string | undefined;
}

/**
 * Individual similar patent reference item in the novelty report.
 */
export interface SimilarPatentItem {
  patentId: string;
  reason: string;
}

/**
 * Feature comparison breakdown comparing user invention features against retrieved patents.
 */
export interface FeatureComparison {
  commonFeatures: string[];
  uniqueFeatures: string[];
  partialOverlap: string[];
}

/**
 * Grounded 7-section AI novelty analysis result generated by Qwen.
 */
export interface NoveltyAnalysisResult {
  summary: string;
  similarPatents: SimilarPatentItem[];
  featureComparison: FeatureComparison;
  novelAspects: string[];
  overlappingClaims: string[];
  risks: string[];
  recommendations: string[];
}

export type RagAnalysisResult = NoveltyAnalysisResult;

/**
 * Section-level relevance contributing to semantic similarity.
 */
export interface RelevantSection {
  section: string;
  reason: string;
}

/**
 * Individual overlapping claim analysis item with overlap strength classification.
 */
export interface OverlappingClaim {
  claimNumber?: number | string | undefined;
  summary: string;
  reason: string;
  overlapStrength: 'High' | 'Medium' | 'Low';
}

/**
 * Complete section and claim overlap analysis payload for a single retrieved patent.
 */
export interface OverlapAnalysisItem {
  patentId: string;
  title: string;
  similarityScore: number;
  relevantSections: RelevantSection[];
  overlappingClaims: OverlappingClaim[];
}

/**
 * Execution latency metrics for the RAG pipeline.
 */
export interface RagMetrics {
  retrievalTimeMs: number;
  promptTimeMs: number;
  llmInferenceTimeMs: number;
  totalTimeMs: number;
  retrievedCount: number;
  overlappingClaimsCount?: number | undefined;
}

export interface RagConfidenceBlock {
  retrieval: { score: number; level: string };
  analysis: { score: number; level: string };
  overall: { score: number; level: string };
}

/**
 * Individual extracted technical feature from invention disclosure deconstruction.
 */
export interface ExtractedFeature {
  id: string;
  name: string;
  description: string;
  category: string;
  importance: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
}

/**
 * Result payload returned by invention feature deconstruction module.
 */
export interface InventionDeconstructionResult {
  coreTitle: string;
  technicalDomain: string[];
  extractedFeatures: ExtractedFeature[];
  isFallback?: boolean | undefined;
}

/**
 * Full response payload returned by POST /api/rag/analyze.
 */
export interface RagAnalysisResponse {
  success: boolean;
  query: string;
  confidence?: RagConfidenceBlock | undefined;
  retrievedPatents?: RagRetrievedPatent[] | undefined;
  analysis: NoveltyAnalysisResult;
  overlapAnalysis?: OverlapAnalysisItem[] | undefined;
  deconstructedFeatures?: InventionDeconstructionResult | undefined;
  metrics?: RagMetrics | undefined;
}

/**
 * Feature Deconstruction Service Contract.
 */
export interface IFeatureDeconstructionService {
  deconstructInvention(input: string | { query?: string; text?: string }): Promise<InventionDeconstructionResult>;
}

/**
 * Primary RAG Service Contract.
 */
export interface IRagService {
  /**
   * Performs retrieval-augmented generation novelty and section/claim overlap analysis.
   */
  analyze(request: RagAnalysisRequest): Promise<RagAnalysisResponse>;

  /**
   * Deconstructs plain text invention query into structured technical features.
   */
  deconstructInvention(input: string | { query?: string; text?: string }): Promise<InventionDeconstructionResult>;

  /**
   * Backward-compatible hybrid ranking method.
   */
  hybridRank(dto: HybridRankingDto): Promise<RankedPatentCandidate[]>;

  /**
   * Backward-compatible cross-encoder reranking method.
   */
  rerankCrossEncoder(candidates: RankedPatentCandidate[], topK?: number): Promise<RankedPatentCandidate[]>;
}

/**
 * Novelty Analysis Service Contract.
 */
export interface INoveltyAnalysisService {
  analyzeNovelty(request: RagAnalysisRequest): Promise<RagAnalysisResponse>;
}

/**
 * Overlap Analysis Service Contract.
 */
export interface IOverlapAnalysisService {
  analyzeOverlap(request: RagAnalysisRequest, searchResults?: SearchResult[]): Promise<OverlapAnalysisItem[]>;
}
