import type { HybridRankingDto, RankedPatentCandidate } from '../dto/rag.dto.js';

/**
 * Incoming request payload for RAG novelty analysis.
 */
export interface RagAnalysisRequest {
  query: string;
  topK?: number | undefined;
}

/**
 * Summary representation of a retrieved prior-art patent included in the RAG response.
 */
export interface RagRetrievedPatent {
  patentId: string;
  title: string;
  score: number;
  ipc?: string | undefined;
  abstract?: string | undefined;
  section?: string | undefined;
}

/**
 * Structured AI novelty analysis output generated by Qwen.
 */
export interface RagAnalysisResult {
  summary: string;
  similarPatents: string;
  novelty: string;
  overlappingClaims: string;
  recommendations: string;
}

/**
 * Execution latency metrics for the RAG pipeline.
 */
export interface RagMetrics {
  retrievalTimeMs: number;
  promptTimeMs: number;
  llmInferenceTimeMs: number;
  totalTimeMs: number;
  retrievedCount: number;
}

/**
 * Full response payload returned by POST /api/rag/analyze.
 */
export interface RagAnalysisResponse {
  success: boolean;
  query: string;
  retrievedPatents: RagRetrievedPatent[];
  analysis: RagAnalysisResult;
  metrics?: RagMetrics | undefined;
}

/**
 * Primary RAG Service Contract.
 */
export interface IRagService {
  /**
   * Performs retrieval-augmented generation novelty analysis on a user invention query.
   */
  analyze(request: RagAnalysisRequest): Promise<RagAnalysisResponse>;

  /**
   * Backward-compatible hybrid ranking method.
   */
  hybridRank(dto: HybridRankingDto): Promise<RankedPatentCandidate[]>;

  /**
   * Backward-compatible cross-encoder reranking method.
   */
  rerankCrossEncoder(candidates: RankedPatentCandidate[], topK?: number): Promise<RankedPatentCandidate[]>;
}
