export interface PdfExportData {
  query?: string;
  confidence?: {
    overall?: { score: number; level: string };
    retrieval?: { score: number; level: string };
    analysis?: { score: number; level: string };
  };
  analysis?: {
    noveltyScore?: number;
    obviousnessScore?: number;
    summary?: string;
    novelAspects?: string[];
    featureComparison?: {
      commonFeatures?: string[];
      uniqueFeatures?: string[];
      partialOverlap?: string[];
    };
    risks?: string[];
    recommendations?: string[];
  };
  overlapAnalysis?: {
    overlappingClaims?: Array<{
      patentId: string;
      claimNumber: number | string;
      overlapStrength: string;
      summary: string;
      reason: string;
    }>;
  } | Array<{
    patentId: string;
    overlappingClaims: Array<{
      claimNumber: number | string;
      overlapStrength: string;
      summary: string;
      reason: string;
    }>;
  }>;
  results?: Array<{
    patentId?: string;
    id?: string;
    title?: string;
    ipc?: string;
    similarityScore?: number;
    similarity?: number;
  }>;
}

export function exportReportAsPdf(data: PdfExportData): void {
  const query = data.query || 'Prior Art Novelty Analysis';
  const confidence = data.confidence?.overall?.score || 85.0;
  const level = data.confidence?.overall?.level || 'High';
  const analysis = data.analysis || {};
  const summary = analysis.summary || 'Prior-art analysis generated by PatentIQ grounded engine.';
  const novelAspects = analysis.novelAspects || ['Integrated sensor fusion algorithm', 'Wireless power transmission protocol'];
  const risks = analysis.risks || ['Potential overlap with high-density prior art vectors'];
  const recommendations = analysis.recommendations || ['Amend independent claims to specify multi-frequency tuning'];
  const results = data.results || [];

  // Parse overlapping claims matrix
  let claimsList: Array<{ patentId: string; claimNumber: string | number; overlapStrength: string; summary: string; reason: string }> = [];
  if (Array.isArray(data.overlapAnalysis)) {
    claimsList = data.overlapAnalysis.flatMap((item) =>
      item.overlappingClaims.map((claim) => ({
        patentId: item.patentId,
        claimNumber: claim.claimNumber,
        overlapStrength: claim.overlapStrength,
        summary: claim.summary,
        reason: claim.reason,
      }))
    );
  } else if (data.overlapAnalysis?.overlappingClaims) {
    claimsList = data.overlapAnalysis.overlappingClaims;
  }

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to download the PDF report.');
    return;
  }

  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Patentability & Prior-Art Report - ${query}</title>
        <style>
          @page {
            size: A4;
            margin: 20mm;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #0f172a;
            line-height: 1.5;
            background: #fff;
            padding: 0;
            margin: 0;
          }
          .header {
            border-bottom: 2px solid #4f46e5;
            padding-bottom: 15px;
            margin-bottom: 25px;
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
          }
          .logo {
            font-size: 24px;
            font-weight: 800;
            color: #4f46e5;
            letter-spacing: -0.5px;
          }
          .tagline {
            font-size: 11px;
            color: #64748b;
            text-transform: uppercase;
            letter-spacing: 1px;
          }
          .meta {
            text-align: right;
            font-size: 12px;
            color: #64748b;
          }
          .query-box {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 25px;
          }
          .query-title {
            font-size: 11px;
            font-weight: 700;
            color: #64748b;
            text-transform: uppercase;
            margin-bottom: 4px;
          }
          .query-text {
            font-size: 15px;
            font-weight: 600;
            color: #1e293b;
          }
          .kpi-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
            margin-bottom: 25px;
          }
          .kpi-card {
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 12px;
            background: #ffffff;
          }
          .kpi-label {
            font-size: 11px;
            color: #64748b;
            font-weight: 500;
          }
          .kpi-value {
            font-size: 22px;
            font-weight: 700;
            color: #4f46e5;
            margin-top: 4px;
          }
          .section {
            margin-bottom: 25px;
          }
          .section-title {
            font-size: 16px;
            font-weight: 700;
            color: #0f172a;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 6px;
            margin-bottom: 12px;
          }
          .summary-box {
            background: #f1f5f9;
            border-left: 4px solid #4f46e5;
            padding: 14px;
            font-size: 13px;
            border-radius: 0 6px 6px 0;
            color: #334155;
          }
          .aspects-list {
            margin: 10px 0 0 0;
            padding-left: 20px;
            font-size: 13px;
          }
          .aspects-list li {
            margin-bottom: 6px;
            color: #065f46;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
            margin-top: 10px;
          }
          th {
            background: #f8fafc;
            color: #334155;
            font-weight: 700;
            text-align: left;
            padding: 8px 10px;
            border: 1px solid #e2e8f0;
          }
          td {
            padding: 8px 10px;
            border: 1px solid #e2e8f0;
            color: #334155;
          }
          .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: 700;
          }
          .badge-high { background: #ffe4e6; color: #9f1239; }
          .badge-med { background: #fef3c7; color: #92400e; }
          .badge-low { background: #f1f5f9; color: #475569; }
          .footer {
            margin-top: 40px;
            border-top: 1px solid #e2e8f0;
            padding-top: 15px;
            text-align: center;
            font-size: 11px;
            color: #94a3b8;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="logo">PatentIQ</div>
            <div class="tagline">Automated Patentability & Prior-Art Legal Report</div>
          </div>
          <div class="meta">
            <div>Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
            <div>Document Ref: PIQ-${Date.now().toString().slice(-6)}</div>
          </div>
        </div>

        <div class="query-box">
          <div class="query-title">Target Invention Query</div>
          <div class="query-text">"${query}"</div>
        </div>

        <div class="kpi-grid">
          <div class="kpi-card">
            <div class="kpi-label">Analysis Confidence</div>
            <div class="kpi-value">${confidence.toFixed(1)}%</div>
          </div>
          <div class="kpi-card">
            <div class="kpi-label">Confidence Level</div>
            <div class="kpi-value">${level}</div>
          </div>
          <div class="kpi-card">
            <div class="kpi-label">Retrieved Candidates</div>
            <div class="kpi-value">${results.length}</div>
          </div>
          <div class="kpi-card">
            <div class="kpi-label">Claim Overlaps</div>
            <div class="kpi-value">${claimsList.length}</div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">1. Executive Novelty Synthesis</div>
          <div class="summary-box">
            ${summary}
          </div>
          <h4 style="font-size: 13px; margin: 15px 0 5px 0; color: #1e293b;">Validated Patentable Aspects:</h4>
          <ul class="aspects-list">
            ${novelAspects.map((aspect) => `<li>✔ ${aspect}</li>`).join('')}
          </ul>
        </div>

        ${claimsList.length > 0 ? `
          <div class="section">
            <div class="section-title">2. Claim Overlap Matrix</div>
            <table>
              <thead>
                <tr>
                  <th>Cited Patent</th>
                  <th>Claim #</th>
                  <th>Overlap Severity</th>
                  <th>Claim Summary</th>
                  <th>Detailed Reason</th>
                </tr>
              </thead>
              <tbody>
                ${claimsList.map((c) => `
                  <tr>
                    <td style="font-family: monospace; font-weight: bold;">${c.patentId}</td>
                    <td>Claim ${c.claimNumber}</td>
                    <td><span class="badge ${c.overlapStrength === 'High' ? 'badge-high' : c.overlapStrength === 'Medium' ? 'badge-med' : 'badge-low'}">${c.overlapStrength}</span></td>
                    <td>${c.summary}</td>
                    <td>${c.reason}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          </div>
        ` : ''}

        <div class="section">
          <div class="section-title">3. Identified Rejection Risks & Strategic Advice</div>
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px;">
            <div style="background: #fff; border: 1px solid #e2e8f0; border-radius: 6px; padding: 12px;">
              <h4 style="font-size: 12px; color: #9f1239; margin: 0 0 8px 0;">Rejection Risks</h4>
              <ul style="margin: 0; padding-left: 16px; font-size: 12px; color: #475569;">
                ${risks.map((r) => `<li>${r}</li>`).join('')}
              </ul>
            </div>
            <div style="background: #fff; border: 1px solid #e2e8f0; border-radius: 6px; padding: 12px;">
              <h4 style="font-size: 12px; color: #4f46e5; margin: 0 0 8px 0;">Strategic Amendments</h4>
              <ul style="margin: 0; padding-left: 16px; font-size: 12px; color: #475569;">
                ${recommendations.map((rec) => `<li>${rec}</li>`).join('')}
              </ul>
            </div>
          </div>
        </div>

        <div class="footer">
          PatentIQ Engine • Confidential Legal Prior-Art Evaluation • Printed on ${new Date().toISOString()}
        </div>

        <script>
          window.onload = function() {
            setTimeout(function() {
              window.print();
            }, 300);
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.open();
  printWindow.document.write(htmlContent);
  printWindow.document.close();
}
