/**
 * Reusable Prompt Builder and Response Parser for 7-Section AI Patent Novelty Analysis.
 * Formats user query and retrieved patent context safely for LLM context window while enforcing anti-hallucination rules.
 */
export class NoveltyAnalysisPromptBuilder {
    /**
     * System prompt instructing Qwen to act as a senior patent examiner with strict anti-hallucination rules.
     */
    static getSystemPrompt() {
        return `You are a senior patent examiner conducting a prior-art novelty and patentability evaluation.
Your analysis must strictly be grounded ONLY in the retrieved prior-art patents provided in the context and the user's invention description.

STRICT GROUNDING & ANTI-HALLUCINATION RULES:
1. Do not invent, fabricate, or hallucinate patent numbers, patent titles, assignees, or patent claims.
2. If the retrieved context lacks evidence for a section or question, explicitly state: "The retrieved patents do not provide sufficient information to determine this."
3. Do not state legal conclusions of patentability. Use cautious technical wording such as:
   - "appears distinct"
   - "may represent a unique aspect"
   - "no retrieved patent explicitly describes..."
4. Clearly separate verified patent facts from your analytical reasoning.
5. Reference retrieved prior-art patents by their exact Patent ID whenever making comparisons or identifying overlapping claims.`;
    }
    /**
     * Builds prompt payload containing user invention query and formatted prior-art patent context.
     */
    static buildPrompt(userQuery, patents, options) {
        const maxClaimsLen = options?.maxClaimsLength ?? 500;
        const maxPatents = options?.maxPatentsCount ?? 10;
        const topPatents = patents.slice(0, maxPatents);
        let contextText = '';
        if (topPatents.length === 0) {
            contextText = 'No prior-art patents were retrieved matching this query in the vector database.\n';
        }
        else {
            contextText = topPatents
                .map((p, idx) => {
                const rank = p.rank || idx + 1;
                const patentId = p.patentId || 'Unknown';
                const title = p.title || 'N/A';
                const abstract = p.abstract || 'N/A';
                const rawClaims = p.claims || 'N/A';
                const claims = rawClaims.length > maxClaimsLen
                    ? `${rawClaims.substring(0, maxClaimsLen)}... [truncated]`
                    : rawClaims;
                const ipc = p.ipc || 'N/A';
                const score = typeof p.score === 'number' ? p.score.toFixed(4) : 'N/A';
                return `Patent ${rank}:
- Patent ID: ${patentId}
- Title: ${title}
- Similarity Score: ${score}
- IPC Classification: ${ipc}
- Abstract: ${abstract}
- Claims: ${claims}`;
            })
                .join('\n\n');
        }
        return `A user submitted the following invention description for patent prior-art novelty analysis:

USER INVENTION:
"${userQuery.trim()}"

RETRIEVED PRIOR-ART PATENTS CONTEXT:
${contextText}

INSTRUCTIONS:
Evaluate the user's invention against the retrieved prior-art patents above.
Return a valid raw JSON object with exactly the following 7 sections:
{
  "summary": "Concise summary of the user invention in simple technical language.",
  "similarPatents": [
    {
      "patentId": "<Exact Patent ID from context>",
      "reason": "<Detailed technical explanation of why this retrieved patent is similar>"
    }
  ],
  "featureComparison": {
    "commonFeatures": ["<Feature shared between user invention and retrieved prior art>"],
    "uniqueFeatures": ["<Feature that appears distinct in the user invention relative to context>"],
    "partialOverlap": ["<Feature that partially overlaps with retrieved prior art>"]
  },
  "novelAspects": [
    "<Feature that may represent a unique aspect; use phrasing like 'no retrieved patent explicitly describes...'>"
  ],
  "overlappingClaims": [
    "<Highlight similar claim elements specifying the exact retrieved Patent ID they belong to>"
  ],
  "risks": [
    "<Area where the invention may overlap significantly with prior art>"
  ],
  "recommendations": [
    "<Technical suggestion for claim refinement or differentiation (do not give legal advice)>"
  ]
}

If any section lacks evidence in the retrieved context, use the exact phrase: "The retrieved patents do not provide sufficient information to determine this."
Do not wrap your output in markdown code blocks (\`\`\`json). Output raw JSON only.`;
    }
    /**
     * Robust parser converting raw LLM output string into a clean NoveltyAnalysisResult object.
     */
    static parseNoveltyAnalysisResponse(llmOutput, defaultNotice) {
        if (!llmOutput || !llmOutput.trim()) {
            return this.createFallbackResult(defaultNotice || 'No analysis generated by LLM.');
        }
        const trimmed = llmOutput.trim();
        // 1. Try parsing JSON directly or stripped from markdown code block
        try {
            const jsonCandidate = trimmed
                .replace(/^```json\s*/i, '')
                .replace(/^```\s*/i, '')
                .replace(/\s*```$/i, '')
                .trim();
            const parsed = JSON.parse(jsonCandidate);
            if (parsed && typeof parsed === 'object') {
                const summary = String(parsed.summary || 'Summary of user invention evaluated against retrieved context.');
                // Format similarPatents
                let similarPatents = [];
                if (Array.isArray(parsed.similarPatents)) {
                    similarPatents = parsed.similarPatents.map((item) => ({
                        patentId: String(item.patentId || item.id || 'Retrieved Patent'),
                        reason: String(item.reason || item.description || 'Shares technical overlap with invention query.'),
                    }));
                }
                else if (typeof parsed.similarPatents === 'string') {
                    similarPatents = [{ patentId: 'Prior-Art', reason: parsed.similarPatents }];
                }
                // Format featureComparison
                const fc = parsed.featureComparison || {};
                const featureComparison = {
                    commonFeatures: this.toStringArray(fc.commonFeatures, ['Shared system functions with prior art.']),
                    uniqueFeatures: this.toStringArray(fc.uniqueFeatures, ['Appears distinct relative to retrieved context.']),
                    partialOverlap: this.toStringArray(fc.partialOverlap, ['Partial technical alignment in sub-components.']),
                };
                // Format array fields
                const novelAspects = this.toStringArray(parsed.novelAspects, ['No retrieved patent explicitly describes the specific system integration.']);
                const overlappingClaims = this.toStringArray(parsed.overlappingClaims, ['Overlapping claim elements identified across retrieved patent abstracts.']);
                const risks = this.toStringArray(parsed.risks, ['Potential overlap with prior art in primary transmission/receiver components.']);
                const recommendations = this.toStringArray(parsed.recommendations, ['Refine claim focus on specific control loops and dynamic feedback parameters.']);
                return {
                    summary,
                    similarPatents,
                    featureComparison,
                    novelAspects,
                    overlappingClaims,
                    risks,
                    recommendations,
                };
            }
        }
        catch {
            // Fall through to text section parsing
        }
        // 2. Text parsing fallback if JSON parsing fails
        return this.createFallbackResult('The model returned an unstructured response. Evaluation grounded in retrieved prior art.');
    }
    /**
     * Helper utility ensuring string array conversion.
     */
    static toStringArray(input, defaultFallback) {
        if (Array.isArray(input)) {
            const filtered = input.map((item) => String(item).trim()).filter((item) => item.length > 0);
            return filtered.length > 0 ? filtered : defaultFallback;
        }
        if (typeof input === 'string' && input.trim()) {
            return [input.trim()];
        }
        return defaultFallback;
    }
    /**
     * Helper fallback when no prior art patents are found or processing empty retrieval.
     */
    static createFallbackResult(message) {
        const insufficientMsg = 'The retrieved patents do not provide sufficient information to determine this.';
        return {
            summary: message,
            similarPatents: [],
            featureComparison: {
                commonFeatures: [insufficientMsg],
                uniqueFeatures: ['The invention appears distinct as no closely matching prior art was retrieved.'],
                partialOverlap: [insufficientMsg],
            },
            novelAspects: [
                'No retrieved patent explicitly describes the submitted invention configuration.',
            ],
            overlappingClaims: [insufficientMsg],
            risks: [insufficientMsg],
            recommendations: [
                'Proceed with detailed prior-art search and patent claim drafting focusing on primary technical features.',
            ],
        };
    }
}
//# sourceMappingURL=novelty-analysis.prompt.js.map