import type { SearchResult } from '../../search/interfaces/search.interface.js';
import type { RagAnalysisResult } from '../interfaces/rag.interface.js';

export interface PromptOptions {
  maxClaimsLength?: number;
  maxPatentsCount?: number;
}

/**
 * Reusable Prompt Builder and Template Engine for Patent Prior-Art Analysis.
 * Formats user query and retrieved patent context safely for LLM context window.
 */
export class PatentAnalysisPromptBuilder {
  /**
   * System prompt instructing Qwen to act as a senior patent examiner.
   */
  public static getSystemPrompt(): string {
    return `You are an expert patent examiner conducting a prior-art novelty and patentability analysis.
Your analysis must strictly be grounded in the retrieved prior-art patents provided in the context.
Do not fabricate or invent patent information, numbers, titles, or claims.
Clearly separate verified patent facts from your analytical reasoning.`;
  }

  /**
   * Builds the prompt payload containing user query and formatted prior-art patent context.
   */
  public static buildPrompt(userQuery: string, patents: SearchResult[], options?: PromptOptions): string {
    const maxClaimsLen = options?.maxClaimsLength ?? 500;
    const maxPatents = options?.maxPatentsCount ?? 10;
    const topPatents = patents.slice(0, maxPatents);

    let contextText = '';

    if (topPatents.length === 0) {
      contextText = 'No prior-art patents were found matching this query in the vector database.\n';
    } else {
      contextText = topPatents
        .map((p, idx) => {
          const rank = p.rank || idx + 1;
          const patentId = p.patentId || 'Unknown';
          const title = p.title || 'N/A';
          const abstract = p.abstract || 'N/A';
          const rawClaims = p.claims || 'N/A';
          const claims =
            rawClaims.length > maxClaimsLen
              ? `${rawClaims.substring(0, maxClaimsLen)}... [truncated]`
              : rawClaims;
          const ipc = p.ipc || 'N/A';
          const score = typeof p.score === 'number' ? p.score.toFixed(4) : 'N/A';

          return `Patent ${rank}:
- Patent ID: ${patentId}
- Title: ${title}
- Similarity Score: ${score}
- IPC Classification: ${ipc}
- Abstract: ${abstract}
- Claims: ${claims}`;
        })
        .join('\n\n');
    }

    return `A user submitted the following invention description for patent prior-art analysis:

USER INVENTION:
"${userQuery.trim()}"

RETRIEVED PRIOR-ART PATENTS:
${contextText}

INSTRUCTIONS:
Evaluate the user's invention against the retrieved prior-art patents above.
Provide your output as a raw JSON object with exactly the following keys:
{
  "summary": "Concise summary of the submitted invention and its core technical domain.",
  "similarPatents": "Detailed identification of similar prior-art patents retrieved (referencing Patent ID, Title, and Similarity Score) and explanation of why they are relevant.",
  "novelty": "Analysis of potential novel aspects or unique features in the user invention that distinguish it from the retrieved prior art.",
  "overlappingClaims": "Specific technical overlaps, features, or claim elements shared between the user invention and the retrieved prior-art patents.",
  "recommendations": "Actionable suggestions for patent drafting, unique focus areas, or claim refinements to maximize patentability."
}

Do not include any Markdown formatting wrappers like \`\`\`json outside the raw JSON object. Ground all conclusions in the provided context.`;
  }

  /**
   * Robust parser converting raw LLM output string into a clean RagAnalysisResult object.
   * Handles JSON strings, markdown JSON codeblocks, or section-header text fallbacks.
   */
  public static parseAnalysisResponse(llmOutput: string, defaultNotice?: string): RagAnalysisResult {
    if (!llmOutput || !llmOutput.trim()) {
      return this.createFallbackResult(defaultNotice || 'No analysis generated by LLM.');
    }

    const trimmed = llmOutput.trim();

    // 1. Try parsing JSON directly or stripped from markdown code block
    try {
      const jsonCandidate = trimmed
        .replace(/^```json\s*/i, '')
        .replace(/^```\s*/i, '')
        .replace(/\s*```$/i, '')
        .trim();

      const parsed = JSON.parse(jsonCandidate);
      if (parsed && typeof parsed === 'object') {
        return {
          summary: String(parsed.summary || 'Summary unavailable.'),
          similarPatents: String(parsed.similarPatents || 'Similar patents breakdown unavailable.'),
          novelty: String(parsed.novelty || 'Novelty assessment unavailable.'),
          overlappingClaims: String(parsed.overlappingClaims || 'Overlapping claims analysis unavailable.'),
          recommendations: String(parsed.recommendations || 'Recommendations unavailable.'),
        };
      }
    } catch {
      // Fall through to text section parsing
    }

    // 2. Section parsing fallback for plain text or markdown output
    const summaryMatch = trimmed.match(/(?:1\.?\s*|summary:?\s*)([\s\S]*?)(?=(?:2\.?|similar|novelty|overlapping|recommendation|$))/i);
    const similarMatch = trimmed.match(/(?:2\.?\s*|similar\s*patents?:?\s*)([\s\S]*?)(?=(?:3\.?|novelty|overlapping|recommendation|$))/i);
    const noveltyMatch = trimmed.match(/(?:3\.?\s*|novelty:?\s*)([\s\S]*?)(?=(?:4\.?|overlapping|recommendation|$))/i);
    const overlapMatch = trimmed.match(/(?:4\.?\s*|overlapping\s*claims?:?\s*)([\s\S]*?)(?=(?:5\.?|recommendation|$))/i);
    const recMatch = trimmed.match(/(?:5\.?\s*|recommendations?:?\s*)([\s\S]*?)$/i);

    return {
      summary: summaryMatch?.[1]?.trim() || trimmed.substring(0, 300) || 'Summary unavailable.',
      similarPatents: similarMatch?.[1]?.trim() || 'Refer to retrieved prior-art patents list.',
      novelty: noveltyMatch?.[1]?.trim() || 'Detailed novelty analysis completed based on retrieved vector embeddings.',
      overlappingClaims: overlapMatch?.[1]?.trim() || 'Technical overlaps identified across retrieved patent sections.',
      recommendations: recMatch?.[1]?.trim() || 'Refine patent claim scope focusing on unique system features.',
    };
  }

  /**
   * Helper fallback when no prior art patents are found.
   */
  public static createFallbackResult(message: string): RagAnalysisResult {
    return {
      summary: message,
      similarPatents: 'No matching prior-art patents found in vector database.',
      novelty: 'The submitted invention appears novel relative to the database, as no closely matching prior art was retrieved.',
      overlappingClaims: 'No overlapping claims identified.',
      recommendations: 'Proceed with detailed prior-art search and patent specification drafting focusing on primary inventive claims.',
    };
  }
}
